name: Howard
favicon: null
layout_spectrum: 0.5191883500665426
typography_spectrum: 0.008413094328716397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7767100208438933
  lightness: 0.6940911959391087
  saturation: 0.07713800412602723
  rhythmicContrast: 0.6481103426776826
purpose: []
